---
title: "HW1 - STA 135"
author: "Gianni Spiga"
date: "3/29/2022"
output: html_document
---



## Problem 1.6
### a.)
```{r}
airpol <-
  read.csv("~/GitHub/STA135/Homework/HW1/Air-Pollution Data G.C.Tao.csv",
           header = TRUE)
library(ggplot2)
library(ggExtra)
library(GGally)

#Pairwise plots
ggpairs(airpol)

#Marginal plots
colnames <- names(airpol)
for (i in colnames[-1]){
  print(ggMarginal(ggplot(airpol, aes_string(x = "Wind..x1.", y = i)) + geom_point(color = 'firebrick'), type = 'histogram', fill = 'dodgerblue'))
}
```
### b.)
```{r}
#xbar, mean vector
colMeans(airpol[sapply(airpol, is.numeric)]) 

#Sn, the COV/VAR marix
n = nrow(airpol)
cov(airpol) * (n-1)/n

# R the correlation matrix
round(cor(airpol),2)
```
We can see that none of the variables have a very high correlation. We can see the highest correlation in our data is between Carbon Monoxide (CO) and Nitrogen Dioxide (NO2) of 0.557. We also can see that Wind is negatively correlated with all pollutants. 


## Problem 1.9

```{r}
#a.)
library(plotly)
x1 <- c(-6, -3, -2, 1, 2, 5, 6, 8)
x2 <- c(-2, -3, 1, -1, 2, 1, 5, 3)
mydata <- data.frame(x1, x2)

#ggplot(aes(x = x1, y = x2)) + geom_point()
fig <- plot_ly(mydata, x = ~x1, y = ~x2)
fig

n = nrow(mydata)
myvarmat = cov(mydata) * (n-1)/n
myvarmat
s11 = myvarmat[1]
s12 = myvarmat[2]
s22 = myvarmat[4]
```


```{r}
#b.) 
#Formula pdf page 56

# x1~ = x1 costheta + x2 sintheta
x1tilde = x1 * 0.899 + x2 * 0.438

# x2~ = -x1 sintheta + x2 costheta
x2tilde = -x1 * 0.438 + x2 * 0.899

#c 
datatilde = data.frame(x1tilde, x2tilde)
n = nrow(datatilde)
diag(var(datatilde))  #* (n-1)/n)

#d
newx1 = 4 * 0.899 + -2 * 0.438
newx2 = -4 * 0.438 + -2 * 0.899

dOP = sqrt((newx1^2/28.462) + (newx2^2/2.022))
dOP

#e
#From footnote
a11 = (0.899^2/(0.899^2 * s11 + 2 * 0.438 * 0.899 * s12 + 0.438^2 * s22)) + (0.438^2/ (0.899^2 * s22 - 2 * 0.438 * 0.899 * s12 + 0.438^2 * s11))

a22 = (0.438^2 / (0.899^2 * s11 + 2 * 0.438 * 0.899 *s12 + 0.438^2 * s22)) + (0.899^2 / (0.899^2 * s22 - 2 * 0.438 * 0.899*s12 + 0.438^2 * s11))

a12 = ((0.438 * 0.899) / (0.899^2 * s11 + 2 * 0.438 * 0.899 * s12 + 0.438^2 * s22)) - ((0.438 * 0.899)/ (0.899^2 * s22 - 2 * 0.438 * 0.899 * s12 + 0.438^2 * s11))

dOP2 = sqrt((a11 * 16) + (2*a12 * 4 * -2) + (a22 * 4))
dOP2
```
We can see that within rounding error, these two distances are about the same. 

## P 1.18
```{r}
WomenTrack <- read.csv("~/Github/STA135/Homework/HW1/National Track Records for Women.csv", header =  TRUE)
WomenTrack

#First, convert last 4 columns into seconds 
WomenTrack[,5:8] = WomenTrack[, 5:8] * 60
WomenTrack

#Second, divide each column by respective meters to get meters per second

```

