---
title: "Homework 4"
author: "Gianni Spiga"
date: "5/10/2022"
output: html_document
---

### P1 
6.8.)
a.)
```{r}
tr1 <- matrix(c(6, 7, 5, 9, 8,6,4,9,7,9), nrow = 2, ncol = 5)
tr1

tr2 <- matrix(c(3, 3, 1, 6, 2,3), nrow = 2, ncol = 3)
tr2

tr3 <- matrix(c(2, 3, 5, 1, 3,1, 2, 3), nrow = 2, ncol = 4)
tr3

xbar1 <- rowMeans(tr1)
xbar1

xbar2 <- rowMeans(tr2)
xbar2

xbar3 <- rowMeans(tr3)
xbar3


#xl1 <- rbind(tr1[1,], tr2[2,], tr3[3,])

xbar <-
  c((ncol(tr1) * xbar1[1] + ncol(tr2) * xbar2[1] + ncol(tr3) * xbar3[1]) / (ncol(tr1) + ncol(tr2) + ncol(tr3)),
    ((ncol(tr1) * xbar1[2]) + (ncol(tr2) * xbar2[2]) + (ncol(tr3) * xbar3[2])) / (ncol(tr1) + ncol(tr2) + ncol(tr3))
  )
xbar


cat("=", )


#xbarl1 <- matrix(4, nrow = 3, ncol = 5) +
# cat("=") 
# matrix(4, nrow = 3, ncol = 5)
# print('+' )
# matrix(c(2,-2,-1), nrow = 3, ncol =5)
# print('+')
# matrix(c(2,-2,-1), nrow = 3, ncol =5)
```
$$
x_{1j} = \begin{pmatrix}
4 & 4 & 4 & 4 & 4 \\
4 & 4 & 4 &\\
4 &4 &4 &4 &\\
\end{pmatrix} + \begin{pmatrix}
2 & 2 & 2 & 2 & 2 \\
-2 & -2 & -2 &\\
-1 & -1 & -1 & -1 &\\
\end{pmatrix} + \begin{pmatrix}
0 & -1 & 2 & -2 & 1 \\
1 & -1 & 0 &\\
-1 & 2 & 0 & -1 &\\
\end{pmatrix}
$$
$$
x_{2j} = \begin{pmatrix}
5 & 5 & 5 & 5 & 5 \\
5 & 5 & 5 &\\
5 &5 &5 &5 &\\
\end{pmatrix} + \begin{pmatrix}
3 & 3 & 3 & 3 & 3 \\
-1 & -1 & -1 &\\
-3 & -3 & -3 & -3 &\\
\end{pmatrix} + \begin{pmatrix}
-1 & 1 & -2 & 1 & 1 \\
-1 & 2 & -1 &\\
-1 & 2 & 0 & -1 &\\
\end{pmatrix}
$$
b.)

```{r}



```
